// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgflYZHOg-qGhvY2iweztT4qKhHCB9YGI',
    appId: '1:159394540313:web:859f2398b15a92276bb388',
    messagingSenderId: '159394540313',
    projectId: 'flutter-firebase-app-89853',
    authDomain: 'flutter-firebase-app-89853.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-89853.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlzpP0piCC4XC5uL7kTXEzBvhAGZMorgQ',
    appId: '1:159394540313:android:c63dd366ec7478666bb388',
    messagingSenderId: '159394540313',
    projectId: 'flutter-firebase-app-89853',
    storageBucket: 'flutter-firebase-app-89853.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjgprr1HCHgNBaQFi8m0VhmNDwtSv5gvM',
    appId: '1:159394540313:ios:2c86b6336e4176c06bb388',
    messagingSenderId: '159394540313',
    projectId: 'flutter-firebase-app-89853',
    storageBucket: 'flutter-firebase-app-89853.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjgprr1HCHgNBaQFi8m0VhmNDwtSv5gvM',
    appId: '1:159394540313:ios:86442f31595c382f6bb388',
    messagingSenderId: '159394540313',
    projectId: 'flutter-firebase-app-89853',
    storageBucket: 'flutter-firebase-app-89853.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
